# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.


main:
  - name: Home
    url: /#top
    weight: 10
  - name: Historie
    url: /#historie
    weight: 20
  - name: Hausarbeiten
    url: hausarbeiten/
    weight: 30
  - name: Events
    weight: 40
    url: event/
  - name: Bewerbung
    weight: 50
    url: bewerbung/