# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
hugoblox:
  schema: "2.0"
  theme:
    mode: system
    pack: "matcha"


  # SEO
  marketing:
    seo:
      site_type: Person
      local_business_type: ''
      org_name: ''
      description: 'A highly-customizable Hugo résumé theme powered by Hugo Blox Builder.'
      twitter: 'GetResearchDev'
    analytics:
      google_analytics: ''
      baidu_tongji: ''
      plausible: ''
      fathom: ''
      pirsch: ''
    verification:
      google: ''
      baidu: ''

  # Site header
  header:
      enable: true
      # Header style variant
      style: navbar                       # navbar | navbar-simple | minimal
      # Stick to top on scroll
      sticky: true
      # Menu alignment
      align: center                       # left | center | right
      # Feature toggles
      search: true
      theme_toggle: false
      theme_picker: false
      language_switcher: false
      # Call-to-action button
      cta:
        enable: true
        text: "internes"
        url: ""

  # Site footer
  footer:
    copyright:
      notice: '© {year} Me. This work is licensed under {license}'
      license:
        enable: true
        allow_derivatives: false
        share_alike: true
        allow_commercial: false

  # Localization
  locale:
    date_format: 'Jan 2, 2006'
    time_format: '3:04 PM'

  # Site features
  features:
    math:
      enable: false
    privacy_pack:
      enable: false
